.gitignore
apps/forms-e2e/.env.test
apps/forms-e2e/.eslintrc.json
apps/forms-e2e/playwright.config.ts
apps/forms-e2e/project.json
apps/forms-e2e/src/data-hunter/data/inputData.json
apps/forms-e2e/src/data-hunter/fixtures/basePage.ts
apps/forms-e2e/src/data-hunter/page-object-model/formPage.ts
apps/forms-e2e/src/data-hunter/tests/formPage.spec.ts
apps/forms-e2e/src/data-hunter/utils/helpers.ts
apps/forms-e2e/src/example.spec.ts
apps/forms-e2e/tsconfig.json
apps/forms/app/[lang]/data-hunter/components/data-hunter-form/data-hunter-form.module.css
libs/ui/src/lib/header/components/menu-language/index.tsx
libs/ui/src/lib/header/components/menu-navigation/index.tsx
libs/ui/src/lib/layout-root/index.tsx
package.json
yarn.lock

resolves https://github.com/Informasjonsforvaltning/fdk-frontend/issues/8

test(data-hunter): add e2e

---

.gitignore
libs/storybook-host/.babelrc
libs/storybook-host/.eslintrc.json
libs/storybook-host/.storybook/main.ts
libs/storybook-host/README.md
libs/storybook-host/package.json
libs/storybook-host/project.json
libs/storybook-host/src/index.ts
libs/storybook-host/src/lib/storybook-host.module.css
libs/storybook-host/src/lib/storybook-host.tsx
libs/storybook-host/tsconfig.json
libs/storybook-host/tsconfig.lib.json
libs/storybook-host/tsconfig.storybook.json
libs/ui/src/lib/test-component/index.tsx
libs/ui/src/lib/test-component/test-component.stories.tsx
nx.json
package.json
tsconfig.base.json
yarn.lock

Ref. #63 
Legger til Storybook i henhold til denne guiden: https://nx.dev/recipes/storybook/one-storybook-for-all
Kjør `yarn storybook` eller `nx storybook storybook-host` for å spinne opp.
La til en test-komponent under `libs/ui` for å demonstrere at det funker. De andre komponentene må muligens tilpasses litt for å gjøre de portable nok til å brukes i stories.

Legger til Storybook

---

apps/docs/public/content/catalogs/datasets/datasets.nb.mdx
apps/docs/public/content/catalogs/datasets/datasets.nn.mdx

fix typo in the first sentence in paragraph "What kind of information can I get?" - norwegian and norwegian nynorsk version.

fix: typo datasets nb and nn

---

apps/docs/public/content/docs/additional-resources/additional-resources.en.mdx
apps/docs/public/content/docs/additional-resources/additional-resources.nb.mdx
apps/docs/public/content/docs/additional-resources/additional-resources.nn.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/1-preparations/1-preparations.en.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/1-preparations/1-preparations.nb.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/1-preparations/1-preparations.nn.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/3-distribution/3-distribution.en.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/3-distribution/3-distribution.nb.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/3-distribution/3-distribution.nn.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/4-data-service/4-data-service.en.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/4-data-service/4-data-service.nb.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/4-data-service/4-data-service.nn.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/5-catalog-and-complete-description/5-catalog-and-complete-description.en.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/5-catalog-and-complete-description/5-catalog-and-complete-description.nb.mdx
apps/docs/public/content/docs/how-to-guides/how-to-dataset/5-catalog-and-complete-description/5-catalog-and-complete-description.nn.mdx

fixes #234 
Løser siste del av https://github.com/Informasjonsforvaltning/fdk-frontend/issues/189

fix(docs): edit additional resources and add info on atlasdcat

---

apps/frontpage/src/app/[lang]/components/frontpage-banner/components/norgeskart/index.tsx

feat: Ad Bronnoysund

---

libs/dictionaries/src/lib/dictionaries/en/frontpage.json
libs/dictionaries/src/lib/dictionaries/nb/frontpage.json
libs/dictionaries/src/lib/dictionaries/nn/frontpage.json

fix(docs): updated ai search popup text

---

libs/ui/src/lib/header/index.tsx

Fikser slik at header sjekker om den skal være "sticky" ved page load i tillegg til scroll.

fix(project): fixed sticky header on page load

---

apps/docs/public/content/catalogs/concepts/concepts.en.mdx
apps/docs/public/content/catalogs/concepts/concepts.nb.mdx
apps/docs/public/content/catalogs/concepts/concepts.nn.mdx
apps/docs/public/content/catalogs/data-services/data-services.en.mdx
apps/docs/public/content/catalogs/data-services/data-services.nb.mdx
apps/docs/public/content/catalogs/data-services/data-services.nn.mdx
apps/docs/public/content/catalogs/datasets/datasets.en.mdx
apps/docs/public/content/catalogs/datasets/datasets.nb.mdx
apps/docs/public/content/catalogs/datasets/datasets.nn.mdx
apps/docs/public/content/catalogs/information-models/information-models.en.mdx
apps/docs/public/content/catalogs/information-models/information-models.nb.mdx
apps/docs/public/content/catalogs/information-models/information-models.nn.mdx
apps/docs/public/content/catalogs/public-services-and-events/public-services-and-events.en.mdx
apps/docs/public/content/catalogs/public-services-and-events/public-services-and-events.nb.mdx
apps/docs/public/content/catalogs/public-services-and-events/public-services-and-events.nn.mdx

Update text and links in the descriptions about the catalogs

fix(docs): update catalogs description pages

---

libs/dictionaries/src/lib/dictionaries/en/common.json
libs/dictionaries/src/lib/dictionaries/nb/common.json
libs/dictionaries/src/lib/dictionaries/nn/common.json

fix(docs): updated catalog descriptions

---

apps/docs/public/content/docs/sharing-data/how-to-dataset/2-dataset-description/2-dataset-description.en.mdx
apps/docs/public/content/docs/sharing-data/how-to-dataset/2-dataset-description/2-dataset-description.nb.mdx
apps/docs/public/content/docs/sharing-data/how-to-dataset/2-dataset-description/2-dataset-description.nn.mdx
apps/docs/public/content/docs/sharing-data/how-to-dataset/7-extras-code-lists/7-extras-code-lists.en.mdx
apps/docs/public/content/docs/sharing-data/how-to-dataset/7-extras-code-lists/7-extras-code-lists.nb.mdx
apps/docs/public/content/docs/sharing-data/how-to-dataset/7-extras-code-lists/7-extras-code-lists.nn.mdx
libs/dictionaries/src/lib/dictionaries/en/docs.json
libs/dictionaries/src/lib/dictionaries/nb/docs.json
libs/dictionaries/src/lib/dictionaries/nn/docs.json

resolves https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1002

docs(docs): add info on codelists

---

apps/docs/public/content/docs/metadata-quality/metadata-quality.en.mdx
apps/docs/public/content/docs/metadata-quality/metadata-quality.nb.mdx
apps/docs/public/content/docs/metadata-quality/metadata-quality.nn.mdx

Fikser tabeller på metadata-artikkel

fix(docs): metadata levels list -> table

---

apps/docs/public/content/docs/resources/resources.en.mdx
apps/docs/public/content/docs/resources/resources.nb.mdx
apps/docs/public/content/docs/resources/resources.nn.mdx

Fikser lesbarhet på ressurs-lister

fix(docs): resources lists formatting

---

libs/dictionaries/src/lib/i18n-config/index.tsx
libs/ui/src/lib/language-switcher/index.tsx

fix(project): removed locale flags

---

apps/data-norge/src/app/components/frontpage/organization-carousel/organizations.json

closes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/309

chore: add skatteetaten to org carousel

---

apps/data-norge/public/content/docs/sharing-data/how-to-dataset/2-dataset-description/2-dataset-description.en.mdx
apps/data-norge/public/content/docs/sharing-data/how-to-dataset/2-dataset-description/2-dataset-description.nb.mdx
apps/data-norge/public/content/docs/sharing-data/how-to-dataset/2-dataset-description/2-dataset-description.nn.mdx

This change adds a link where the user can read more about URIs.

Change:Add link to more information about URIs to 2-dataset-description.nb.mdx 

---

apps/data-norge/public/content/docs/finding-data/access-data/access-data.en.mdx
apps/data-norge/public/content/docs/finding-data/access-data/access-data.nb.mdx
apps/data-norge/public/content/docs/finding-data/access-data/access-data.nn.mdx
apps/data-norge/src/app/components/docs/docs-page/index.tsx

skal fikse at denne gir 404: https://data.norge.no/nb/docs/finding-data/access-data

fix(docs): fixed bug where access-data page resulted in 404

---

apps/data-norge/src/app/components/frontpage/frontpage-banner/components/scroll-button/scroll-button.module.scss
apps/data-norge/src/app/components/frontpage/frontpage-banner/frontpage-banner.module.scss
apps/data-norge/src/app/components/frontpage/frontpage-banner/index.tsx
apps/data-norge/src/app/components/frontpage/student-survey-banner/index.tsx
apps/data-norge/src/app/components/frontpage/student-survey-banner/styles.module.scss

feat: frontpage student banner

---

apps/data-norge/src/app/components/details-page/dataset-tags/index.tsx

fix(details): fallback to code when theme lacks title/prefLabel

---

apps/data-norge/public/content/about/about.en.mdx
apps/data-norge/public/content/about/about.nb.mdx
apps/data-norge/public/content/about/about.nn.mdx

Changes are made after input from our legal resource. We have focused on using the correct terms and downplaying private organizations.

Chore: Update about.nb.mdx

---

apps/data-norge/src/app/[lang]/access-request/[...slug]/page.tsx
apps/data-norge/src/app/[lang]/datasets/[id]/page.tsx
apps/data-norge/src/app/components/details-page/dataset/index.tsx
libs/ui/src/lib/access-request-button/index.tsx
libs/ui/src/lib/resource-not-available-notice/index.tsx

Fixes this: https://digdir.slack.com/archives/C05TE7H2BEG/p1744368959599629

fix: access request 404

---

apps/data-norge/src/app/[lang]/datasets/[id]/page.tsx
libs/data-access/src/lib/community/api/index.ts

chore(details): debug logging for missing community topics

---

apps/data-norge/public/content/technical/api/api.en.mdx
apps/data-norge/public/content/technical/api/api.nb.mdx
apps/data-norge/public/content/technical/api/api.nn.mdx

Dokumentatsjon feilløsning #1146

fix: fix documentation links

---

apps/data-norge/public/content/docs/sharing-data/how-to-dataset/how-to-dataset.en.mdx
apps/data-norge/public/content/docs/sharing-data/how-to-dataset/how-to-dataset.nb.mdx
apps/data-norge/public/content/docs/sharing-data/how-to-dataset/how-to-dataset.nn.mdx
apps/data-norge/public/content/docs/sharing-data/rdf/rdf.en.mdx
apps/data-norge/public/content/docs/sharing-data/rdf/rdf.nb.mdx
apps/data-norge/public/content/docs/sharing-data/rdf/rdf.nn.mdx

fix: make numbered lists instead of points

---

apps/data-norge/public/content/docs/docs.en.mdx
apps/data-norge/public/content/docs/docs.nb.mdx
apps/data-norge/public/content/docs/docs.nn.mdx

fix: use new paths

---

.github/ISSUE_TEMPLATE/feature_requests.md

Adds type Feature to the template feature-requests and removes label:Enhancement

Add type to feature_requests.md

---

.github/ISSUE_TEMPLATE/bug_report.md

Adds type Bug to the template bug_report and removes label: Bug.

Add type to bug_report.md

---

.github/ISSUE_TEMPLATE/ux_issue.md

Adds type: Feature to the template for ux_issue.

Add type to ux_issue.md

---

apps/data-norge/src/app/components/details-page/dataset/index.tsx
libs/ui/src/lib/access-request-button/index.tsx
libs/ui/src/lib/dataset-preview-widget/index.tsx
libs/utils/src/lib/siteimprove-analytics/index.ts

Tracks:
- click on "Use dataset" button
- click on "Request access" button
- click on "Show dataset preview" button
Ref. #433

feat: added siteimprove tracking

---

apps/data-norge/src/app/[lang]/datasets/[id]/page.tsx
libs/data-access/src/lib/search-service/api/index.ts

resolves https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1178
also refactor/cleanup some bloat

fix: use resource uri not identifier for relations lookup

---

apps/data-norge/public/content/docs/sharing-data/rdf/rdf-crash-course/rdf-crash-course.nb.mdx

Resolves https://github.com/Informasjonsforvaltning/fdk-frontend/issues/519

Fix: typo in rdf-crash-course.nb.mdx

---

apps/data-norge/src/app/components/details-page/distributions/index.tsx

fix: include example data check when rendering

---

apps/data-norge/src/app/components/frontpage/share-data-banner/index.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/568 , fixes https://github.com/Informasjonsforvaltning/fdk-frontend/issues/595

Fix landing page 404
